### ISSUE TITLE
Something is deleting remote data: Cannot read property 12 of undefined

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#370]
There should be a data array for every remote on construction. Something is removing it

![image](https://user-images.githubusercontent.com/48334001/208793995-36be76bb-f865-4780-8ee1-fd8bd6c21160.png)

This is the resulting error, when we try to access a property of data but data doesn't exist:

```json
TypeError: Cannot read property 12 of undefined
    at RemoteData (../src/room/commune/remotesManager.ts:151:34)
    at run (../src/room/commune/commune.ts:206:28)
    at apply (../src/other/screeps-profiler.ts:104:32)
    at run (../src/room/rooms.ts:40:61)
    at roomsManager (../src/main.ts:96:8)
    at callback (../src/other/screeps-profiler.ts:480:15)
    at wrap (../src/main.ts:50:13)
    at loop (../src/other/ErrorMapper.ts:78:16)```

**Comment by pieterbrandsen** [comment]
Stale, re-open if issue persists
