### ISSUE TITLE
TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by Aerics84** [CarsonBurke/The-Internationale-Screeps-Bot#557]
On the latest dev:
```
TypeError: Cannot read property 'x' of undefined
    at packAsNum  (../src/international/utils.ts:473:16)
    at CommunePlanner.planSourceStructures  (../src/room/communePlanner.ts:1134:32)
    at CommunePlanner.preTickRun  (../src/room/communePlanner.ts:360:13)
    at Object.Room.createWorkRequest  (../src/room/roomFunctions.ts:2148:55)
    at Object.Room.basicScout  (../src/room/roomFunctions.ts:909:9)
    at RoomManager.update  (../src/room/room.ts:92:17)
    at TickConfig.configRooms  (../src/international/tickConfig.ts:92:29)
    at TickConfig.run  (../src/international/tickConfig.ts:45:13)
    at profiler.wrap  (../src/main.ts:83:19)
    at Object.wrap  (../src/other/profiler.ts:480:15)
```

**Comment by CarsonBurke** [comment]
I'm not sure how this could happen. The code seems to have the necessary safety checks?
```ts
        for (let i = 0; i < this.sourceStructureCoords.length; i++) {
            let closestCoordIndex: number
            let closestRange = Infinity

            for (let j = this.sourceStructureCoords[i].length - 1; j >= 0; j--) {
                const coord = this.sourceStructureCoords[i][j]
                const packedCoord = packAsNum(coord)

                if (this.minCutCoords.has(packedCoord)) {
                    this.sourceStructureCoords[i].splice(j, 1)
                    this.roadCoords[packedCoord] = 0
                    continue
                }

                const range = getRange(hubAnchor, coord)
                if (range >= closestRange) continue

                closestCoordIndex = j
                closestRange = range
            }

            if (!closestCoordIndex) continue

            const closestCoord = this.sourceStructureCoords[i][closestCoordIndex]
            this.sourceStructureCoords[i].splice(closestCoordIndex, 1)

            sourceLinkCoords.push(closestCoord)

            const packedCoord = packAsNum(closestCoord)
        )
```

**Comment by Aerics84** [comment]
happens with the latest dev, again:
```
TypeError: Cannot read property 'x' of undefined
    at packAsNum  (../src/international/utils.ts:473:16)
    at CommunePlanner.findDynamicStampAnchorWeighted  (../src/room/communePlanner.ts:1518:60)
    at CommunePlanner.planStamps  (../src/room/communePlanner.ts:1270:39)
    at CommunePlanner.hub  (../src/room/communePlanner.ts:1905:13)
    at CommunePlanner.preTickRun  (../src/room/communePlanner.ts:348:13)
    at Object.Room.createWorkRequest  (../src/room/roomFunctions.ts:2148:55)
    at Object.Room.advancedScout  (../src/room/roomFunctions.ts:949:13)
    at Function.roleManager  (../src/room/creeps/roleManagers/international/scout.ts:233:21)
    at Function.wrappedFunction  (../src/other/profiler.ts:104:32)
    at CreepRoleManager.runManager  (../src/room/creeps/creepRoleManager.ts:54:27)
```

**Comment by Aerics84** [comment]
```
TypeError: Cannot read property 'x' of undefined
    at CommunePlanner.findSourceHarvestPositions  (../src/room/communePlanner.ts:997:51)
    at CommunePlanner.preTickRun  (../src/room/communePlanner.ts:347:13)
    at Object.Room.createWorkRequest  (../src/room/roomFunctions.ts:2384:55)
    at Object.Room.advancedScout  (../src/room/roomFunctions.ts:1006:13)
    at Function.roleManager  (../src/room/creeps/roleManagers/international/scout.ts:233:21)
    at Function.wrappedFunction  (../src/other/profiler.ts:104:32)
    at CreepRoleManager.runManager  (../src/room/creeps/creepRoleManager.ts:54:27)
    at CreepRoleManager.run  (../src/room/creeps/creepRoleManager.ts:29:44)
    at RoomManager.run  (../src/room/room.ts:174:30)
    at roomsManager  (../src/room/rooms.ts:38:30)
```
