### ISSUE TITLE
TypeError: Cannot read property 'structureType' of undefined

### ISSUE THREAD

**Issue by Aerics84** [CarsonBurke/The-Internationale-Screeps-Bot#558]
On latest dev:
```
TypeError: Cannot read property 'structureType' of undefined
    at cSite.room.findCSiteAtCoord.cSite  (../src/room/creeps/roleManagers/remote/remoteSourceHarvester.ts:225:74)
    at Object.Room.findCSiteAtXY  (../src/room/roomFunctions.ts:2372:12)
    at Object.Room.findCSiteAtCoord  (../src/room/roomFunctions.ts:2359:16)
    at RemoteHarvester.buildContainer  (../src/room/creeps/roleManagers/remote/remoteSourceHarvester.ts:225:32)
    at RemoteHarvester.wrappedFunction  (../src/other/profiler.ts:104:32)
    at RemoteHarvester.remoteActions  (../src/room/creeps/roleManagers/remote/remoteSourceHarvester.ts:167:17)
    at RemoteHarvester.wrappedFunction  (../src/other/profiler.ts:104:32)
    at Function.roleManager  (../src/room/creeps/roleManagers/remote/remoteSourceHarvester.ts:331:22)
    at Function.wrappedFunction  (../src/other/profiler.ts:104:32)
    at CreepRoleManager.runManager  (../src/room/creeps/creepRoleManager.ts:54:27)
```

**Comment by CarsonBurke** [comment]
### Theory

cSiteUpdate (and structureUpdate) are activating for a tick. If we aren't checking for the update that tick, it may simply not know to update.

### Solution

-Attach to RoomManager
-delete relevant data instead of modifying values like cSiteUpdate (remove cSiteUpdate and structureUpdate)
