### ISSUE TITLE
Unable to determine type of room(remote) after clearing memory.

### ISSUE THREAD

**Issue by realacesu** [CarsonBurke/The-Internationale-Screeps-Bot#734]
**Commit or otherwise version of the bot**
a9565efdb28da7ddfed7e0c0f59ac9fceafc09bd
**Describe the bug**
When a remote room is reserved, after clearing memory; the room is shown as 'undefined' causing the error

**Expected behaviour**

Unknown 

**How can we reproduce this?**

Have a reserved remote and `clearMemory()` I believe once a creep enters the room it errors

**Potential fix**

With a reserved room present after a memory reset - assign it as a remote in Memory and abandon it

**Applicable media**
 
``` 
TypeError: Cannot set property '0' of undefined
    at RemotesManager.initRun  (../src/room/commune/remotesManager.ts:44:63)
    at RemotesManager.wrappedFunction  (../src/other/profiler.ts:104:32)
    at CommuneManager.initRun  (../src/room/commune/commune.ts:313:28)
    at CommuneManager.wrappedFunction  (../src/other/profiler.ts:104:32)
    at RoomManager.initRun  (../src/room/room.ts:268:37)
    at RoomManager.wrappedFunction  (../src/other/profiler.ts:104:32)
    at RoomsManager.initRun  (../src/room/rooms.ts:42:29)
    at profiler.wrap  (../src/main.ts:82:21)
    at Object.wrap  (../src/other/profiler.ts:480:15)
    at originalLoop  (../src/main.ts:65:13)
```

**Comment by realacesu** [comment]
even after the room loses its reserved status, it remains undefined

**Comment by CarsonBurke** [comment]
I believe this is resolved in latest
